version: '3'

services:

  dd-agent:
    image: datadog/docker-dd-agent
    env_file:           
      - .env_datadog    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

  https-portal:         
    restart: always     
    image: steveltn/https-portal:1
    ports:              
      - '80:80'         
      - '443:443'       
    links:                                                                                                                                                                                       
      - redmine         
    depends_on:         
      - redmine         
    environment:        
      USERMAP_UID: 1000 
      USERMAP_GID: 1000 
      STAGE: 'production'                                                                                                                                                                        
      DOMAINS: 'redmine-osaka.net -> http://redmine:80'
    volumes:            
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./data/ssl-cert:/var/lib/https-portal
                        
  postgresql:
    container_name: postgresql
    image: sameersbn/postgresql:9.6-4
    environment:
      - DB_USER=redmine
      - DB_PASS=password
      - DB_NAME=redmine_prod
      - DEBUG=false
      - USERMAP_UID=1000
      - USERMAP_GID=1000

    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro 
      - ./data/pg:/var/lib/postgresql

  redmine:              
    restart: always     
    image: sameersbn/redmine:4.0.3-1
    env_file:           
      - .env_redmine    
    ports:              
      - "80"            
    volumes:            
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./data/redmine:/home/redmine/data
